#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🤜 Yeah, ton commit est validé ! 🤛"
echo "-----------------------------------------"
echo "\n les 5 derniers commits :"
git log --oneline --graph --all -n 5
echo "-----------------------------------------"